---
name: Run Cppcheck

on:
  push:
    branches:
      - main
      - dev
      - 'hotfixes/**'
      - 'releases/**'
  pull_request:
    branches:
      - main
      - dev
      - 'hotfixes/**'
      - 'releases/**'

jobs:
  cppcheck_ubuntu:
    name: Check C++ code with Cppcheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
          
      - name: Check C++ code
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
...
