---
name: Run flawfinder

on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    branches:
      - main
      - 'releases/**'

jobs:
  flawfinder_ubuntu:
    name: Check C++ code with flawfinder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.0.2
          
      - name: Check C++ code
        uses: deep5050/flawfinder-action@1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
...
