---
name: Run Super-Linter

on:
  push:
    branches:
      - main
      - dev
      - 'hotfixes/**'
      - 'releases/**'
  pull_request:
    branches:
      - main
      - dev
      - 'hotfixes/**'
      - 'releases/**'

jobs:
  super_linter_ubuntu:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Super-Linter against the code base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
...
